# Frase na tela - Implemente um programa que imprima na tela a frase "O primeiro programa a gente nunca esquece!".
print("Nota fiscal")
print("                          ")
print("Frutas               Valor")
print("======               =====")
print("Maçã                  4,50")
print("Banana                2,47")
print("Melancia              1,20")
print("Kiwi                 10,23")
print("Abacate               9,89")
